"use client";
import { useState, useCallback } from "react";
import {
  BedDouble,
  Bot,
  CalendarDays,
  CheckCircle2,
  CircleDollarSign,
  Clock3,
  Download,
  Hotel,
  LoaderCircle,
  MapPin,
  ShieldCheck,
  Sparkles,
  UtensilsCrossed,
} from "lucide-react";
import { motion } from "framer-motion";
import toast from "react-hot-toast";

import { generateTripPlan } from "../../services/tripPlannerService";
import { tourismDiscoveryService } from "../../services/tourismDiscoveryService";
import { useInternetStatus } from "../../hooks/useInternetStatus";
import type { GeneratedTripPlan } from "../../types/tripPlanner";
import type { TravelMood, BudgetAnalysis } from "../../types/tourism";
import { TRAVEL_MOODS, TRAVEL_MOOD_LABELS } from "../../types/tourism";

const MOOD_EMOJIS: Record<string, string> = {
  relax: "🧘", adventure: "🏔️", romantic: "💕", family: "👨‍👩‍👧‍👦",
  food: "🍜", photography: "📸", history: "🏛️", beach: "🏖️",
  snow: "❄️", nature: "🌿", luxury: "💎", budget: "💰",
};

const AIPlannerEnhanced = () => {
  const online = useInternetStatus();
  const [destination, setDestination] = useState("");
  const [days, setDays] = useState(3);
  const [budget, setBudget] = useState(50000);
  const [currency, setCurrency] = useState("PKR");
  const [tripType, setTripType] = useState("Family");
  const [transport, setTransport] = useState("Car");
  const [travelMood, setTravelMood] = useState<TravelMood>("relax");
  const [loading, setLoading] = useState(false);
  const [plan, setPlan] = useState<GeneratedTripPlan | null>(null);
  const [budgetResult, setBudgetResult] = useState<BudgetAnalysis | null>(null);


  const handleGenerate = useCallback(async () => {
    if (!destination.trim()) {
      toast.error("Please enter a destination.");
      return;
    }
    if (days < 1 || days > 30) {
      toast.error("Trip days must be between 1 and 30.");
      return;
    }
    if (budget <= 0) {
      toast.error("Please enter a valid budget.");
      return;
    }
    if (!online) {
      toast.error("Trip planning needs an internet connection.");
      return;
    }

    setLoading(true);
    try {
      const generated = await generateTripPlan({
        destination: destination.trim(),
        days,
        budget,
        currency,
        tripType,
        transport,
      });
      setPlan(generated);

      // Calculate budget analysis
      const budgetAnalysis = tourismDiscoveryService.calculateBudget(
        budget,
        days,
        tripType === "Solo" ? 1 : tripType === "Couple" ? 2 : 4,
        destination,
        currency
      );
      setBudgetResult(budgetAnalysis);

      toast.success("Your personalized trip plan is ready!");
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Unable to generate trip plan.");
    } finally {
      setLoading(false);
    }
  }, [destination, days, budget, currency, tripType, transport, online]);

  const downloadPlan = useCallback(() => {
    if (!plan || !budgetResult) return;
    const lines = [
      `═══════════════════════════════════════`,
      `  NEXUS MAP - AI TRIP PLAN`,
      `═══════════════════════════════════════`,
      ``,
      `📍 Destination: ${plan.destination}`,
      `📅 Duration: ${plan.days} days`,
      `💰 Budget: ${plan.currency} ${plan.budget.toLocaleString()}`,
      `🎯 Trip Type: ${plan.tripType}`,
      `🚗 Transport: ${plan.transport}`,
      `😊 Mood: ${travelMood}`,
      ``,
      `BUDGET ANALYSIS`,
      `  Score: ${budgetResult.score}/100 (${budgetResult.scoreLabel})`,
      `  Total Estimated: ${budgetResult.currency} ${budgetResult.totalEstimated.toLocaleString()}`,
      `  Daily Average: ${budgetResult.currency} ${budgetResult.dailyAverage.toLocaleString()}`,
      ``,
      ...budgetResult.breakdown.map(
        (item) => `  ${item.label}: ${budgetResult.currency} ${item.estimatedCost.toLocaleString()} (${item.percentage}%)`
      ),
      ``,
      `HOTEL: ${plan.hotelSuggestion}`,
      `FOOD: ${plan.foodSuggestion}`,
      ``,
      `ITINERARY`,
      ...plan.itinerary.flatMap((day) => [
        `─── Day ${day.day}: ${day.title} ───`,
        day.summary,
        ...day.activities.map(
          (a) => `  ${a.time} - ${a.title}: ${a.description}`
        ),
        `  Daily cost: ${plan.currency} ${day.estimatedDailyCost.toLocaleString()}`,
        ``,
      ]),
      `PACKING LIST`,
      ...plan.packingList.map((item) => `  ✓ ${item}`),
      ``,
      `SAFETY TIPS`,
      ...plan.safetyTips.map((item) => `  • ${item}`),
      ``,
      `═══════════════════════════════════════`,
      `  Generated by Nexus Map AI`,
      `═══════════════════════════════════════`,
    ];

    const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `${plan.destination.toLowerCase().replaceAll(" ", "-")}-trip-plan.txt`;
    anchor.click();
    URL.revokeObjectURL(url);
    toast.success("Plan downloaded!");
  }, [plan, budgetResult, travelMood]);

  return (
    <section className="nexus-page nexus-page-body">
      <div className="nexus-container">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 18 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center"
        >
          <p className="nexus-eyebrow">AI Travel Assistant</p>
          <h1 className="text-hero-display mt-4 text-5xl sm:text-6xl">
            Build Your Perfect Trip with{" "}
            <span className="nexus-gradient-text">Nexus AI</span>
          </h1>
          <p className="mx-auto mt-4 max-w-3xl text-slate-400">
            Smart budget analysis, personalized packing lists, local food suggestions, and detailed day-by-day itineraries.
          </p>
        </motion.div>

        <div className="mt-12 grid gap-8 xl:grid-cols-[400px_1fr]">
          {/* Form Sidebar */}
          <div className="nexus-card-elevated self-start p-6 xl:sticky xl:top-24">
            <div className="flex items-center gap-3">
              <Bot className="text-cyan-400" size={24} />
              <h2 className="text-xl font-bold text-white">Create Your Journey</h2>
            </div>

            <div className="mt-6 space-y-4">
              <label className="block">
                <span className="mb-2 block text-sm text-slate-400">Destination</span>
                <div className="nexus-input flex items-center gap-3">
                  <MapPin size={18} className="text-cyan-400" />
                  <input
                    value={destination}
                    onChange={(e) => setDestination(e.target.value)}
                    className="min-w-0 flex-1 bg-transparent outline-none"
                    placeholder="Hunza Valley, Skardu, Dubai..."
                  />
                </div>
              </label>

              <div className="grid grid-cols-2 gap-4">
                <label>
                  <span className="mb-2 block text-sm text-slate-400">Days</span>
                  <div className="nexus-input flex items-center gap-3">
                    <CalendarDays size={18} className="text-cyan-400" />
                    <input type="number" min={1} max={30} value={days}
                      onChange={(e) => setDays(Number(e.target.value))}
                      className="min-w-0 flex-1 bg-transparent outline-none" />
                  </div>
                </label>
                <label>
                  <span className="mb-2 block text-sm text-slate-400">Budget</span>
                  <div className="nexus-input flex items-center gap-3">
                    <CircleDollarSign size={18} className="text-purple-400" />
                    <input type="number" min={1} value={budget}
                      onChange={(e) => setBudget(Number(e.target.value))}
                      className="min-w-0 flex-1 bg-transparent outline-none" />
                  </div>
                </label>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <label>
                  <span className="mb-2 block text-sm text-slate-400">Trip Type</span>
                  <select value={tripType}
                    onChange={(e) => setTripType(e.target.value)}
                    className="nexus-input">
                    <option>Family</option><option>Solo</option>
                    <option>Couple</option><option>Friends</option>
                    <option>Business</option><option>Adventure</option>
                  </select>
                </label>
                <label>
                  <span className="mb-2 block text-sm text-slate-400">Transport</span>
                  <select value={transport}
                    onChange={(e) => setTransport(e.target.value)}
                    className="nexus-input">
                    <option>Car</option><option>Bus</option>
                    <option>Train</option><option>Flight</option>
                    <option>Motorcycle</option><option>Bicycle</option>
                  </select>
                </label>
              </div>

              <label>
                <span className="mb-2 block text-sm text-slate-400">Currency</span>
                <select value={currency}
                  onChange={(e) => setCurrency(e.target.value)}
                  className="nexus-input">
                  <option>PKR</option><option>USD</option>
                  <option>SAR</option><option>AED</option>
                  <option>GBP</option><option>EUR</option>
                </select>
              </label>

              {/* Mood Selector */}
              <div>
                <span className="mb-2 block text-sm text-slate-400">Travel Mood</span>
                <div className="flex flex-wrap gap-1.5">
                  {TRAVEL_MOODS.map((mood) => (
                    <button
                      key={mood}
                      onClick={() => setTravelMood(mood)}
                      className={`rounded-full border px-2.5 py-1 text-xs transition-all ${
                        travelMood === mood
                          ? "border-purple-400/30 bg-purple-400/10 text-purple-300"
                          : "border-white/[0.06] text-slate-500 hover:text-white"
                      }`}
                    >
                      {MOOD_EMOJIS[mood]} {TRAVEL_MOOD_LABELS[mood]}
                    </button>
                  ))}
                </div>
              </div>

              <button
                onClick={handleGenerate}
                disabled={loading}
                className="nexus-button-primary w-full py-4"
              >
                {loading ? (
                  <LoaderCircle className="animate-spin" size={20} />
                ) : (
                  <Sparkles size={20} />
                )}
                {loading ? "Creating..." : "Generate AI Plan"}
              </button>
            </div>
          </div>

          {/* Results */}
          <div className="nexus-card-elevated p-6">
            {!plan ? (
              <div className="flex min-h-[500px] flex-col items-center justify-center text-center">
                <Sparkles size={54} className="text-purple-400" />
                <h2 className="mt-6 text-3xl font-bold text-white">Your itinerary will appear here</h2>
                <p className="mt-3 max-w-xl text-slate-400">
                  Fill in your trip details and generate a complete day-by-day plan with budget breakdown, packing list, and local recommendations.
                </p>
              </div>
            ) : (
              <>
                {/* Plan Header */}
                <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start">
                  <div>
                    <p className="nexus-eyebrow">Generated Itinerary</p>
                    <h2 className="mt-3 text-3xl font-bold text-white">{plan.destination}</h2>
                    <p className="mt-2 text-slate-400">
                      {plan.days}-day {plan.tripType.toLowerCase()} trip · {plan.transport} · {TRAVEL_MOOD_LABELS[travelMood]}
                    </p>
                  </div>
                  <button onClick={downloadPlan} className="nexus-button-glossy">
                    <Download size={17} /> Download Plan
                  </button>
                </div>

                {/* Budget Score */}
                {budgetResult && (
                  <div className="nexus-card-elevated mt-6 p-5 bg-gradient-to-r from-emerald-500/5 to-cyan-500/5">
                    <div className="flex items-center gap-4">
                      <div className="text-center">
                        <p className="text-3xl font-bold text-white">{budgetResult.score}</p>
                        <p className="text-xs text-slate-400">/100</p>
                      </div>
                      <div className="flex-1">
                        <p className="font-semibold text-white">Budget Score: {budgetResult.scoreLabel}</p>
                        <p className="text-sm text-slate-400">
                          {budgetResult.currency} {budgetResult.totalEstimated.toLocaleString()} total · {budgetResult.currency} {budgetResult.dailyAverage.toLocaleString()}/day
                        </p>
                        <div className="mt-2 h-2 rounded-full bg-white/[0.06]">
                          <div
                            className="h-full rounded-full bg-gradient-to-r from-emerald-500 to-cyan-500"
                            style={{ width: `${budgetResult.score}%` }}
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                )}

                {/* Summary Cards */}
                <div className="mt-6 grid gap-4 sm:grid-cols-3">
                  <div className="rounded-2xl border border-white/[0.06] bg-slate-950/40 p-4">
                    <Hotel className="text-cyan-400" size={21} />
                    <p className="mt-3 text-xs uppercase tracking-wider text-slate-500">Hotel</p>
                    <p className="mt-1 text-sm font-semibold text-white">{plan.hotelSuggestion}</p>
                  </div>
                  <div className="rounded-2xl border border-white/[0.06] bg-slate-950/40 p-4">
                    <UtensilsCrossed className="text-purple-400" size={21} />
                    <p className="mt-3 text-xs uppercase tracking-wider text-slate-500">Food</p>
                    <p className="mt-1 text-sm font-semibold text-white">{plan.foodSuggestion}</p>
                  </div>
                  <div className="rounded-2xl border border-white/[0.06] bg-slate-950/40 p-4">
                    <CircleDollarSign className="text-emerald-400" size={21} />
                    <p className="mt-3 text-xs uppercase tracking-wider text-slate-500">Total Cost</p>
                    <p className="mt-1 text-sm font-semibold text-white">
                      {plan.currency} {plan.estimatedTotalCost.toLocaleString()}
                    </p>
                  </div>
                </div>

                {/* Itinerary */}
                <div className="mt-6 space-y-5">
                  {plan.itinerary.map((day) => (
                    <article key={day.day} className="rounded-2xl border border-white/[0.06] bg-slate-950/35 p-5">
                      <div className="flex items-start justify-between gap-4">
                        <div>
                          <p className="text-sm font-semibold text-cyan-400">Day {day.day}</p>
                          <h3 className="mt-1 text-xl font-bold text-white">{day.title}</h3>
                          <p className="mt-2 text-sm text-slate-400">{day.summary}</p>
                        </div>
                        <div className="rounded-xl bg-emerald-400/10 px-3 py-2 text-sm text-emerald-300 whitespace-nowrap">
                          {plan.currency} {day.estimatedDailyCost.toLocaleString()}
                        </div>
                      </div>

                      <div className="mt-4 space-y-2">
                        {day.activities.map((activity, idx) => (
                          <div key={`${day.day}-${idx}`}
                            className="grid gap-2 rounded-xl border border-white/[0.05] bg-white/[0.02] p-3 sm:grid-cols-[80px_1fr_auto]"
                          >
                            <div className="flex items-center gap-2 text-sm text-cyan-300">
                              <Clock3 size={14} />
                              {activity.time}
                            </div>
                            <div>
                              <p className="text-sm font-semibold text-white">{activity.title}</p>
                              <p className="text-xs text-slate-400">{activity.description}</p>
                            </div>
                            <div className="text-xs text-slate-500">
                              {plan.currency} {activity.estimatedCost.toLocaleString()}
                            </div>
                          </div>
                        ))}
                      </div>
                    </article>
                  ))}
                </div>

                {/* Packing & Safety */}
                <div className="mt-6 grid gap-5 lg:grid-cols-2">
                  <div className="rounded-2xl border border-white/[0.06] bg-white/[0.02] p-5">
                    <div className="flex items-center gap-3">
                      <BedDouble className="text-purple-400" size={20} />
                      <h3 className="text-lg font-bold text-white">Packing List</h3>
                    </div>
                    <div className="mt-4 grid gap-2 sm:grid-cols-2">
                      {plan.packingList.map((item) => (
                        <p key={item} className="flex items-center gap-2 text-sm text-slate-300">
                          <CheckCircle2 size={14} className="text-emerald-400 shrink-0" />
                          {item}
                        </p>
                      ))}
                    </div>
                  </div>

                  <div className="rounded-2xl border border-white/[0.06] bg-white/[0.02] p-5">
                    <div className="flex items-center gap-3">
                      <ShieldCheck className="text-cyan-400" size={20} />
                      <h3 className="text-lg font-bold text-white">Safety Tips</h3>
                    </div>
                    <div className="mt-4 space-y-2">
                      {plan.safetyTips.map((item) => (
                        <p key={item} className="flex items-start gap-2 text-sm text-slate-300">
                          <CheckCircle2 size={14} className="mt-0.5 shrink-0 text-emerald-400" />
                          {item}
                        </p>
                      ))}
                    </div>
                  </div>
                </div>
              </>
            )}
          </div>
        </div>
      </div>
    </section>
  );
};

export default AIPlannerEnhanced;
