import { Router } from "express";

import { adminRouter } from "./admin.routes.js";
import { communityNotesRouter } from "./communityNotes.routes.js";
import { favoritesRouter } from "./favorites.routes.js";
import { healthRouter } from "./health.routes.js";
import { historyRouter } from "./history.routes.js";
import { navigationRouter } from "./navigation.routes.js";
import { notificationsRouter } from "./notifications.routes.js";
import { offlineMapsRouter } from "./offlineMaps.routes.js";
import { placesRouter } from "./places.routes.js";
import { reportsRouter } from "./reports.routes.js";
import { tripPlannerRouter } from "./tripPlanner.routes.js";
import { roadAlertsRouter } from "./roadAlerts.routes.js";
import { offlinePacksRouter } from "./offlinePacks.routes.js";
export const apiRouter = Router();
apiRouter.use("/offline-packs", offlinePacksRouter);
apiRouter.use("/health", healthRouter);
apiRouter.use("/road-alerts", roadAlertsRouter);
apiRouter.use("/navigation", navigationRouter);
apiRouter.use("/community", communityNotesRouter);
apiRouter.use("/places", placesRouter);
apiRouter.use("/reports", reportsRouter);
apiRouter.use("/favorites", favoritesRouter);
apiRouter.use("/history", historyRouter);
apiRouter.use("/notifications", notificationsRouter);
apiRouter.use("/offline-maps", offlineMapsRouter);
apiRouter.use("/trip-planner", tripPlannerRouter);
apiRouter.use("/admin", adminRouter);
